export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';
export const LOGIN = 'LOGIN';
export const CHANGE_CURR_NICKNAME = 'CHANGE_CURR_NICKNAME';
export const SET_REPO_ACTIVE = 'SET_REPO_ACTIVE';
export const DEACTIVATE_REPO = 'DEACTIVATE_REPO';
export const CHANGE_CURR_REPOS_PAGE = 'CHANGE_CURR_REPOS_PAGE';
export const RESET_STORE = 'RESET_STORE';
export const SET_COMPARE_NICKNAME = 'SET_COMPARE_NICKNAME';