export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';
export const LOGIN = 'LOGIN';
export const CHANGE_CURR_NICKNAME = 'CHANGE_CURR_NICKNAME';
export const SET_REPO_ACTIVE = 'SET_REPO_ACTIVE';
export const CHANGE_CURR_REPOS_PAGE = 'CHANGE_CURR_REPOS_PAGE';